# Importing Libraries

In [10]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import unicodedata

# Build Cosine Similarity Matrix

In [2]:
df = pd.read_pickle('../models/movies.pkl')

In [3]:
df.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                     combined_vector  
0  [-0.1620263159275055, 0.12982472777366638, -0....  
1  [-0.37325799465179443, 0.038260865956544876, -...  
2  [-0.2768787145614624, -0.5192937254905701, -0....  
3  [0.15796813368797302, 0.19392867386341095, -0....  
4  [-0.07674223184585571, 0.04946580156683922, -0...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   id               4800 non-null   int64 
 1   title            4800 non-null   object
 2   combined_vector  4800 non-null   object
dtypes: int64(1), object(2)
memory usage: 112.6+ KB


In [5]:
vector_matrix = np.vstack(df['combined_vector'].values)
similarity = cosine_similarity(vector_matrix)

In [6]:
print(similarity)

[[1.         0.92772825 0.86237849 ... 0.80724776 0.76075033 0.74917085]
 [0.92772825 1.         0.85983509 ... 0.85053232 0.81787527 0.78863923]
 [0.86237849 0.85983509 1.         ... 0.87825029 0.83866956 0.78207056]
 ...
 [0.80724776 0.85053232 0.87825029 ... 1.         0.92522087 0.89143217]
 [0.76075033 0.81787527 0.83866956 ... 0.92522087 1.         0.90973808]
 [0.74917085 0.78863923 0.78207056 ... 0.89143217 0.90973808 1.        ]]


In [7]:
similarity.shape

(4800, 4800)

# Define Recommendation Function

In [8]:
def recommend(movie):
    matched = df[df['title'] == movie]
    if matched.empty:
        print("it is not in database")
        return
    movie_index = matched.index[0]
    distances = similarity[movie_index]
    movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movie_list:
        print(df.iloc[i[0]].title)

In [9]:
recommend('Spider-Man 3')

Avengers: Age of Ultron
Superman
Mystery Men
Time Bandits
Superman III


# Save Similarity Matrix for Future Use

In [12]:
data = pd.DataFrame(similarity)
data.to_csv("../models/similarityMat.csv",index=False)